# Generated by Django 2.0 on 2018-01-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quests_completed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='quests_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
