# Generated by Django 2.0 on 2018-01-08 12:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='puzzles_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(1, 1), size=None),
            preserve_default=False,
        ),
    ]
