# Generated by Django 2.0 on 2018-01-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
