# Generated by Django 2.0 on 2017-12-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_moderated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.CharField(max_length=100)),
                ('is_moderated', models.BooleanField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Place')),
            ],
        ),
        migrations.AddField(
            model_name='fact',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Place'),
        ),
    ]
