# Generated by Django 2.0 on 2018-01-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='added_by',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puzzle',
            name='added_by',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
